// The coverage run: for every recorded list and record, the columns and kinds the terminal shows with the hand
// hint file, with the spec's derived kinds alone, and with inference alone, so the hand file's contribution is
// measured, not claimed. Then every hand hint file against the derived kinds: which of its facts the spec already
// settles. Writes docs/coverage.md. `pnpm coverage`.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseEnvelope, type Rec } from "../src/envelope.ts";
import { chooseColumns, infer } from "../src/infer.ts";
import { hasHandHints, hintsWith, type Hints, type SpecKind } from "../src/hints.ts";

const repo = join(import.meta.dirname, "..");
const fixtures = join(repo, "tests", "fixtures");
const hintsDir = join(repo, "src", "hints");

type Mode = "hand" | "spec" | "none";
const USE: Record<Mode, { hand: boolean; spec: boolean }> = { hand: { hand: true, spec: true }, spec: { hand: false, spec: true }, none: { hand: false, spec: false } };

/** `products.list.json` → `products list`; `payouts.methods.limits.json` → `payouts methods` (a variant of the same rows). */
function commandOf(file: string): [string, string] | undefined {
  const parts = file.replace(/\.json$/, "").split(".");
  if (parts.length < 2 || ["schema", "error", "help"].includes(parts[0])) return undefined;
  return [parts[0], parts[1]];
}

function columnsFor(rows: Rec[], hints: Hints): string[] {
  return chooseColumns(rows, hints, "normal").map((c) => {
    const r = rows.find((x) => x[c.key] != null) ?? rows[0];
    return `${c.key}:${infer(c.key, r[c.key], r, hints).kind}`;
  });
}

function recordKinds(record: Rec, hints: Hints): string[] {
  return Object.entries(record)
    .map(([k, v]) => [k, infer(k, v, record, hints).kind] as const)
    .filter(([, kind]) => kind !== "hidden" && kind !== "empty")
    .map(([k, kind]) => `${k}:${kind}`);
}

const diff = (a: string[], b: string[]) => {
  const only = (x: string[], y: string[]) => x.filter((v) => !y.includes(v));
  const gone = only(a, b);
  const added = only(b, a);
  if (!gone.length && !added.length) return a.join(",") === b.join(",") ? "same" : "same set, other order";
  return [gone.length ? `−${gone.join(" ")}` : "", added.length ? `+${added.join(" ")}` : ""].filter(Boolean).join(" ");
};

const lines: string[] = [];
lines.push("# Coverage: what the hand hints add over the spec", "", `Generated by \`pnpm coverage\` on ${new Date().toISOString().slice(0, 10)}. Three renderings of every recorded envelope: with the hand hint file over the spec's derived kinds (what ships), with the derived kinds alone, and with inference alone. A row that says \`same\` in the spec column is a hand file that changes nothing for that command.`, "");

// --- 1. recorded lists
lines.push("## Recorded lists", "", "Columns as `key:kind`, at the normal breakpoint, from the first non-empty row.", "", "| command | hand file | with hand hints | spec only vs hand | inference only vs hand |", "|---|---|---|---|---|");
let same = 0;
let total = 0;
for (const file of readdirSync(fixtures).sort()) {
  const cmd = commandOf(file);
  if (!cmd) continue;
  const p = parseEnvelope(readFileSync(join(fixtures, file), "utf8"));
  if (!p.ok || p.payload.kind !== "page" || !p.payload.rows.length) continue;
  const rows = p.payload.rows;
  const by = Object.fromEntries((["hand", "spec", "none"] as Mode[]).map((m) => [m, columnsFor(rows, hintsWith(cmd[0], cmd[1], USE[m]))])) as Record<Mode, string[]>;
  const specVs = diff(by.hand, by.spec);
  total++;
  if (specVs === "same") same++;
  lines.push(`| \`${cmd.join(" ")}\` (${file}) | ${hasHandHints(cmd[0], cmd[1]) ? "yes" : "no"} | ${by.hand.join(", ")} | ${specVs} | ${diff(by.hand, by.none)} |`);
}
lines.push("", `${same} of ${total} recorded lists render the same columns from the spec alone.`, "");

// --- 2. recorded records
lines.push("## Recorded records", "", "Every shown field as `key:kind`; only the differences are listed.", "", "| command | hand file | fields shown | spec only vs hand | inference only vs hand |", "|---|---|---|---|---|");
for (const file of readdirSync(fixtures).sort()) {
  const cmd = commandOf(file);
  if (!cmd) continue;
  const p = parseEnvelope(readFileSync(join(fixtures, file), "utf8"));
  if (!p.ok || !("record" in p.payload) || p.payload.kind === "status") continue;
  const record = p.payload.record;
  const by = Object.fromEntries((["hand", "spec", "none"] as Mode[]).map((m) => [m, recordKinds(record, hintsWith(cmd[0], cmd[1], USE[m]))])) as Record<Mode, string[]>;
  lines.push(`| \`${cmd.join(" ")}\` (${file}) | ${hasHandHints(cmd[0], cmd[1]) ? "yes" : "no"} | ${by.hand.length} | ${diff(by.hand, by.spec)} | ${diff(by.hand, by.none)} |`);
}
lines.push("");

// --- 3. every hand file against the derived kinds
lines.push("## Every hand hint file against the spec", "", "Per file: the facts it states, and which of them the derived kinds already settle. `columns`, `labels`, `primary`, and `relation` are product choices the spec cannot make; they are listed, not judged.", "", "| file | money | status | date | plan | hidden | product choices |", "|---|---|---|---|---|---|---|");
const judge = (want: string[] | undefined, kinds: Record<string, SpecKind> | undefined, kind: SpecKind): string => {
  if (!want?.length) return "";
  const covered = want.filter((k) => kinds?.[k] === kind);
  return covered.length === want.length ? `all ${want.length} in spec` : `${covered.length} of ${want.length} in spec (${want.filter((k) => !covered.includes(k)).join(", ")} not)`;
};
let files = 0;
let fullyCovered = 0;
for (const file of readdirSync(hintsDir).sort()) {
  if (!file.endsWith(".json") || file.startsWith("_")) continue;
  files++;
  const [group, verb] = file.replace(/\.json$/, "").split(".");
  const hand = JSON.parse(readFileSync(join(hintsDir, file), "utf8")) as Hints;
  const kinds = hintsWith(group, verb, USE.spec).kinds;
  const cells = [
    judge(hand.money, kinds, "money"),
    hand.status ? (kinds?.[hand.status] === "status" ? "in spec" : `${hand.status} not`) : "",
    hand.date ? (kinds?.[hand.date] === "date" ? "in spec" : `${hand.date} not`) : "",
    hand.plan ? (kinds?.[hand.plan] === "plan" ? "in spec" : `${hand.plan} not`) : "",
    judge(hand.hidden, kinds, "hidden"),
  ];
  const choices = [hand.primary ? `primary=${hand.primary}` : "", hand.columns ? `columns(${hand.columns.length})` : "", hand.labels ? `labels(${Object.keys(hand.labels).length})` : "", hand.relation ? `relation=${hand.relation}` : "", hand.formatted ? "formatted" : ""].filter(Boolean).join(" ");
  const factsOnly = cells.every((c) => c === "" || /^in spec$|^all \d+ in spec$/.test(c));
  if (factsOnly && !hand.columns && !hand.labels && !hand.primary && !hand.relation) fullyCovered++;
  lines.push(`| ${file} | ${cells.join(" | ")} | ${choices} |`);
}
lines.push("", `${files} hand hint files. ${fullyCovered} say nothing the spec does not.`, "");

writeFileSync(join(repo, "docs", "coverage.md"), lines.join("\n"));
console.error(`docs/coverage.md: ${total} lists, ${files} hint files`);
