// Regenerates the command reference inside each skill's references/commands.md and copies the shared gate from the live `whop`: every GTM group's
// verbs, their kind (read, write, money, destructive), and the flags the schema marks required. Flag names
// drift with the CLI; the skill points at `wv agent <group>` for the rest. Run by `pnpm skill`.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { cachedHelpText, schema } from "../src/runner.ts";
import { parseHelp } from "../src/views/help.ts";
import { markers } from "../src/views/manifest.ts";

const SKILLS: Record<string, string[]> = {
  "whop-gtm": [
    "people", "events", "audiences", "media", "files", "social-accounts", "ad-campaigns", "ad-groups", "ads",
    "promo-codes", "checkout-configurations", "plans", "products", "partners", "bounties", "bounty-submissions",
    "memberships", "stats", "exports", "economic-intelligence", "webhooks",
  ],
  "whop-money": ["payouts", "ledgers", "transfers", "swaps", "deposits", "cards", "verifications", "exports", "accounts"],
};
const START = "<!-- wv agent:start -->";
const END = "<!-- wv agent:end -->";

const root = parseHelp(cachedHelpText([]));
const version = /^(whop@\S+)/.exec(cachedHelpText([]))?.[1] ?? "whop";
const gate = readFileSync(join(import.meta.dirname, "..", "skills", "_shared", "gate.md"), "utf8");

for (const [skill, GROUPS] of Object.entries(SKILLS)) {
  const lines: string[] = [START, "", `Generated by \`pnpm skill\` from ${version} · API ${root.api ?? "?"}. \`wv agent <group>\` prints every flag with its type and description; this is the map.`, ""];
  for (const group of GROUPS) {
    const desc = root.groups.flatMap((g) => g.entries).find((e) => e.name === group)?.desc;
    if (!desc) {
      console.error(`skip ${group}: not in whop --help`);
      continue;
    }
    lines.push(`### ${group}`, "", `${desc} · \`wv agent ${group}\``, "");
    for (const e of parseHelp(cachedHelpText([group])).groups.flatMap((g) => g.entries)) {
      const s = schema(group, e.name) as { options?: { required?: string[] } } | null;
      const required = s?.options?.required ?? [];
      const kind = markers(group, e.name).join(", ");
      lines.push(`- \`whop ${group} ${e.name}\` · ${kind}${required.length ? ` · required: ${required.map((r) => `\`--${r}\``).join(", ")}` : ""}`);
    }
    lines.push("");
  }
  lines.push(END);
  const file = join(import.meta.dirname, "..", "skills", skill, "references", "commands.md");
  const text = readFileSync(file, "utf8");
  const a = text.indexOf(START);
  const b = text.indexOf(END);
  if (a < 0 || b < 0) {
    console.error(`${skill}/references/commands.md has no ${START} … ${END} markers`);
    process.exit(1);
  }
  writeFileSync(file, text.slice(0, a) + lines.join("\n") + text.slice(b + END.length));
  // The rules every skill shares, copied so each skill is self-contained when installed.
  writeFileSync(join(import.meta.dirname, "..", "skills", skill, "references", "gate.md"), gate);
  console.log(`${skill}: command reference regenerated for ${GROUPS.length} groups, gate.md copied`);
}
