// Every string a person reads.

import { shellJoin } from "./argv.ts";

export type Mode = "production" | "sandbox";

const duration = (seconds: number) => (seconds % 60 === 0 ? `${seconds / 60} minute${seconds === 60 ? "" : "s"}` : `${seconds} seconds`);

export const copy = {
  list: {
    of: (n: number, total: number | null) => (total == null || total === n ? `${n} ${n === 1 ? "row" : "rows"}` : `${n} of ${total}`),
    noMore: "no more pages",
    next: (cursor: string) => `next: --after ${cursor}`,
    /** `noun` is the group, or the verb when it names a sub-resource: `payouts methods` has no methods yet, not no payouts. */
    empty: (noun: string) => `No ${noun.replace(/[-_]/g, " ")} yet.`,
    emptyHint: (group: string) => ["whop", group, "create", "--help"],
    json: "json",
    allPages: (pages: number) => `${pages} pages · every row`,
  },
  summary: {
    total: (n: number) => `${n} total`,
    facet: (facet: string) => `By ${facet.replace(/_/g, " ")}`,
    empty: "Nothing to count yet.",
  },
  detail: {
    sections: {
      identity: "Identity",
      status: "Status",
      money: "Money",
      dates: "Dates",
      relations: "Relations",
      other: "Details",
    },
    yes: "yes",
    no: "no",
    empty: "—",
    /** A boolean the hints name as the status: `success` on a webhook delivery. */
    ok: "ok",
    failed: "failed",
  },
  confirm: {
    title: (group: string, verb: string) => `${VERB_TITLES[verb] ?? titleVerb(verb)} ${GROUP_NOUNS[group] ?? group.replace(/-/g, " ")}`,
    badge: (mode: Mode) => (mode === "sandbox" ? "writes to sandbox" : "writes to production"),
    warning: "This runs against production. The Whop CLI has no dry-run.",
    sandboxWarning: "This runs against the sandbox host. No real money moves.",
    money: "This moves real money.",
    expires: (seconds: number) => `The prompt expires in ${duration(seconds)}.`,
    question: "Run it?",
    yesNo: "[y/N]",
    /** Money: the person types the amount back. `y` is not consent for a payout. */
    typeAmount: (amount: string) => `Type ${amount} to send it`,
    amountNo: (amount: string) => `[${amount}/N]`,
    aborted: "Not run.",
    expired: (seconds: number) => `Not run. The prompt sat for ${duration(seconds)}.`,
    /** The before-and-after section of a write against a record wv could read. */
    changes: "Changes",
    record: "record",
    unset: "—",
    deleted: "deleted",
    /** Row labels the money gate adds on top of the flags. */
    to: "to",
    from: "from",
    balance: "balance",
    cap: "cap",
    available: (available: string, after: string) => `${available} available · ${after} after`,
    perPayout: (cap: string) => `${cap} per payout`,
    /** Whop's live limit for the chosen speed sits next to wv's own cap. */
    whopLimit: (max: string, speed: string) => `${max} ${speed} from Whop`,
    wvCap: (cap: string) => `${cap} from wv`,
    dailyLeft: (left: string) => `${left} left today`,
    noCap: "none",
    unknownMethod: "not among the saved payout methods",
    tryFirst: "try first",
    refused: {
      cap: "Over the payout cap",
      balance: "Over the available balance",
      whop: "Whop would refuse this payout",
      whopBody: (amount: string, max: string, speed: string) => `${amount} is more than the ${max} Whop allows per ${speed} payout right now.`,
      badge: "not run",
      capBody: (amount: string, cap: string) => `${amount} is more than the ${cap} cap wv allows per payout.`,
      balanceBody: (amount: string, available: string) => `${amount} is more than the ${available} available in this currency.`,
      raise: (dollars: number) => `Raise it for one shell with WV_PAYOUT_CAP=${dollars}, or turn it off with WV_PAYOUT_CAP=none.`,
      sandbox: "Try it against the sandbox first:",
    },
  },
  adplan: {
    planBadge: "plan only · nothing runs",
    planNote: "Nothing was written. Run the command without --plan to be asked.",
    thenRun: "then",
    money: "Spend accrues as ads deliver and is charged afterward.",
    reachErrorNote: "Whop could not estimate reach, so the create may fail the same way.",
    /** Row keys. */
    campaign: "campaign",
    group: "group",
    ad: "ad",
    reachKey: "reach",
    spend: "spend",
    paysFrom: "pays from",
    runsUnder: "runs under",
    /** Sub-row keys. */
    objective: "objective",
    platform: "platform",
    budget: "budget",
    status: "status",
    goal: "goal",
    targeting: "targeting",
    runs: "runs",
    creative: "creative",
    url: "url",
    new: "new",
    day: "day",
    lifetime: "lifetime",
    onGroups: "on each ad group",
    on: (event: string) => `on ${event.replace(/_/g, " ")}`,
    window: (from?: string, to?: string) => (from && to ? `${from} to ${to}` : from ? `from ${from}` : `until ${to}`),
    creatives: "creatives",
    headline: "headline",
    headlines: "headlines",
    text: "primary text",
    texts: "primary texts",
    description: "description",
    descriptions: "descriptions",
    boostsPost: "boosts an existing post",
    excluding: (n: number) => `excluding ${n} ${n === 1 ? "place" : "places"}`,
    automaticAudience: "automatic audience",
    automaticPlacements: "automatic placements",
    placements: (platforms: string[]) => `placements on ${platforms.join(", ")}`,
    ages: (lo?: number, hi?: number) => (lo !== undefined && hi !== undefined ? `ages ${lo}–${hi}` : lo !== undefined ? `ages ${lo}+` : `ages up to ${hi}`),
    audiences: (names: string[]) => `audiences: ${names.join(", ")}`,
    excludingAudiences: (names: string[]) => `excluding: ${names.join(", ")}`,
    reach: (range: string, platform: string) => `${range} people on ${platform}`,
    reachNone: (platform: string) => `${platform} returned no estimate for this targeting`,
    reachFailed: (message: string) => `not estimated · ${message}`,
    reachSkipped: "not estimated · no targeting on the command line",
    openEnded: (total: string, days: number) => `${total} over ${days} days · no end date`,
    until: (total: string, days: number) => `${total} over ${days} ${days === 1 ? "day" : "days"}`,
    fromExisting: (owner: string) => `from the existing ${owner} budget`,
    noBudget: "none yet · nothing delivers until a budget exists",
    noPaymentMethod: "no ads payment method on the account",
    available: (amount: string) => `${amount} available`,
    noSocial: "no page connected · whop social-accounts connect --platform meta_business --scopes advertise",
    cap: (cap: string) => `${cap} committed spend per plan from wv`,
    typeBudget: (amount: string) => `Type ${amount} to create it`,
    refused: {
      title: "Over the ad spend cap",
      body: (total: string, cap: string) => `This plan commits ${total}, more than the ${cap} cap wv allows per ad write.`,
      raise: (dollars: number) => `Raise it for one shell with WV_AD_CAP=${dollars}, set an end date so the commitment is real, or turn it off with WV_AD_CAP=none.`,
    },
  },
  error: {
    titles: {
      COMMAND_NOT_FOUND: "Not a command",
      HTTP_400: "Whop refused the request",
      HTTP_404: "Not found",
      HTTP_422: "Whop refused the request",
      UNAVAILABLE: "Not available on this business yet",
      HTTP_401: "Not signed in",
      HTTP_403: "Missing permission",
      HTTP_429: "Rate limited",
      VALIDATION_ERROR: "Missing or invalid flags",
      UNKNOWN: "Whop returned an error",
      NOT_JSON: "Not a JSON response",
      ENOENT: "Whop CLI not found",
      NO_TTY: "Needs a terminal",
      SANDBOX_AUTH: "The sandbox refused this login",
      JSON_FLAGS: "Could not assemble the JSON flag",
    } as Record<string, string>,
    fixes: {
      HTTP_401: "whop login",
      HTTP_403: "whop login --api-key",
      SANDBOX_AUTH: "wv sandbox status",
      ENOENT: "curl -fsSL https://whop.com/install.sh | sh",
    } as Record<string, string>,
    fix: "fix",
    /** What unlocks a feature gate, in one line each. */
    gates: {
      preference: "A preference on the business turns it on; nothing to buy.",
      internal: "Whop-internal only. No plan or preference unlocks it outside Whop.",
      cards: "Card issuing needs a verified identity first; Whop opens the Rain account once verification passes.",
      unknown: "Whop turns this on per business. No CLI preference is known for it; ask Whop, or look in the dashboard.",
    },
    field: (path: string, msg: string) => `--${path}  ${msg}`,
    suggested: "Suggested commands:",
  },
  help: {
    hint: "type wv <group> --help",
    groupHint: (group: string) => `type wv ${group} <command> --help`,
    api: "API",
  },
  gtm: {
    title: "gtm",
    window: (days: number, from: string, to: string) => `last ${days} days · ${from} to ${to}`,
    funnel: "Funnel",
    visits: "store visits",
    newUsersKey: "new users",
    revenue: "gross revenue",
    adSpend: "ad spend",
    peopleTitle: "People",
    seen: (days: number) => `seen · ${days}d`,
    people: (seen: string, customers: number, contactable: number, attributed: number) => `${seen} people · ${customers} customers · ${contactable} contactable · ${attributed} attributed to a source`,
    noPeople: "nobody seen in the window",
    audiences: "Audiences",
    none: "—",
    noAudiences: "none yet · whop audiences create --help",
    lookalike: "lookalike",
    members: (n: number) => `${n} people`,
    campaigns: "Campaigns",
    noCampaigns: "No campaigns yet.",
    try: "try",
    offers: "Offers",
    noOffers: "none yet · whop promo-codes create --help",
    off: "off",
    newUsers: "new buyers only",
    churned: "churned buyers only",
    existing: "existing members only",
    uses: (uses: number, stock?: number) => (stock !== undefined && Number.isFinite(stock) ? `${uses} of ${stock} used` : `${uses} used`),
    expires: (date: string) => `expires ${date}`,
    gapsTitle: "Before a launch",
    fix: "fix",
    gap: {
      pixel: "No visit carries a source: the pixel is not installed on your pages, so nothing is attributed.",
      page: "No Meta page is connected, so every ad command will refuse.",
      payment: "No ads payment method on the account, so ads will not deliver.",
      ei: "Economic Intelligence is off, so `whop economic-intelligence` returns 403.",
    },
  },
  doctor: {
    title: "doctor",
    fix: "fix",
    dashboard: "dashboard only",
    labels: {
      auth: "signed in",
      identity: "identity",
      apiKey: "api key",
      pixel: "pixel",
      page: "meta page",
      payment: "ads payment",
      ei: "intelligence",
      products: "products",
      webhooks: "webhooks",
    },
    notSignedIn: "Not signed in.",
    verification: (status: string) => `verification ${status.replace(/_/g, " ")}`,
    payoutsBlocked: (reason: string) => `Payouts are blocked: ${reason}`,
    payoutsAllowed: (max: string) => `payouts allowed · up to ${max} per standard payout`,
    limitsUnreadable: (err: string) => `Could not read the payout limits · ${err}`,
    limitsMissing: "This login cannot read the payout limits (needs payout:withdrawal:read), so identity is unknown.",
    keyActive: (name: string) => `profile ${name} · api key · every checked scope granted`,
    keyLacks: (name: string, actions: string[]) => `profile ${name} · api key · lacks ${actions.join(", ")} · edit the key in the dashboard`,
    oauthFine: (alt: string) => `oauth · every checked scope granted · api-key profile ${alt} also saved`,
    oauthLacks: (actions: string[], alt: string) => `This oauth login lacks ${actions.join(", ")}. The api-key profile ${alt} is saved; switch to it for those.`,
    noKey: "No api-key profile. Webhooks and the other developer scopes refuse an oauth login.",
    noKeyLacks: (actions: string[]) => `No api-key profile, and this oauth login lacks ${actions.join(", ")}. Mint a key in the dashboard, then save it as a profile.`,
    noPeople: "Nobody has been seen yet, so the pixel is unverified.",
    attributed: (attributed: number, seen: number) => `${attributed} of ${seen} people attributed to a source`,
    paymentOn: (n: number) => (n === 1 ? "1 ads payment method on the account" : `${n} ads payment methods on the account`),
    eiOn: "on",
    noProducts: "No products. Nothing can be bought.",
    noSellable: (n: number) => `${n} ${n === 1 ? "product" : "products"}, none visible with a plan. Nothing can be bought.`,
    forSale: (n: number, title: string, price: string) => (n === 1 ? `1 for sale · ${title} · ${price}` : `${n} for sale · ${title} · ${price} · ${n - 1} more`),
    webhooksScope: "Webhooks refuse an oauth login. Sign in with an API key to list, create, or test them.",
    noWebhooks: "No webhooks. Your server hears nothing when someone pays.",
    delivered: (url: string, when: string) => `${url} · last success ${when}`,
    noDelivery: (url: string, days: number) => `${url} · no successful delivery in ${days} days`,
    more: (n: number) => `${n} more`,
    blocking: (n: number) => `${n} blocking`,
    warnings: (n: number) => `${n} ${n === 1 ? "warning" : "warnings"}`,
    ok: (n: number) => `${n} ok`,
  },
  sandbox: {
    title: "sandbox",
    reachable: "reachable",
    unreachable: "not reachable with this key",
    host: "host",
    key: "key",
    account: "account",
    noKey: "none · every call will answer 401",
    source: (source: "env" | "config" | "default" | "none", configPath: string) => (source === "env" ? "from the shell" : source === "config" ? `from ${configPath}` : source === "default" ? "Whop's published sandbox server" : ""),
    badge: "sandbox · no key",
    missingTitle: "The sandbox needs its own key",
    rejectsOauth: "The sandbox host answers every call with 401 unless it gets a sandbox API key; your production login does not work there.",
    whereFrom: "Whop's API reference lists the host but not where its keys are issued, so get one from Whop.",
    docs: "https://docs.whop.com/developer/api/getting-started",
    saveHint: (configPath: string) => `wv keeps it in ${configPath}, owner-only, so no shell variable is needed. WV_SANDBOX_KEY still wins when set.`,
    askKey: "Paste a sandbox key to save it, or press enter to continue without one",
    askHint: "[whop_…/enter]",
    saved: (configPath: string) => `Saved to ${configPath}. Sandbox commands use it from now on.`,
    skipped: "Continuing without a key. Expect 401 from the sandbox host.",
    notAKey: "That does not look like a Whop key (they start with whop_). Nothing saved.",
    keyRejected: (masked: string) => `The sandbox host answered 401 to the key ${masked}. It is not a sandbox key, or it was revoked.`,
    unknownVerb: (verb: string) => `wv sandbox has no '${verb}'. Try wv sandbox status.`,
  },
  jsonFlags: {
    title: "Could not assemble the JSON flag",
    noFile: (path: string) => `@${path}: no such file. A value that starts with @ and names a path is read as JSON.`,
    badFile: (path: string, why: string) => `@${path} is not JSON: ${why}`,
    mixed: (path: string) => `--${path} mixes an array index with an object key on the same node.`,
  },
  license: {
    title: "license",
    valid: "valid",
    invalid: "invalid",
    unknown: "unknown",
    notFound: "No membership carries this key.",
    status: "status",
    product: "product",
    plan: "plan",
    expires: "expires",
    noExpiry: "never · one-time purchase",
    cancels: "cancels then",
    user: "user",
    membership: "membership",
    needsKey: "wv memberships check needs a license key: wv memberships check <key>",
  },
  webhook: {
    title: "webhook test",
    resultTitle: "Test event",
    newest: "Newest delivery",
    result: "result",
    acknowledged: "acknowledged · the endpoint answered 2xx",
    notAcknowledged: "not acknowledged",
    code: "code",
    body: "body",
    event: "event",
    status: "status",
    ok: "ok",
    failed: "failed",
    time: "time",
    seconds: (s: number) => (s < 1 ? `${Math.round(s * 1000)}ms` : `${s.toFixed(2)}s`),
    sent: "sent",
    replayOf: "replay of",
    id: "id",
    noDeliveries: "no delivery recorded yet",
  },
  logs: {
    title: "logs",
    empty: "No log lines in the window. Whop keeps hosted app logs for 7 days.",
    oldestFirst: "oldest first",
    follow: "follow",
    following: (seconds: number) => `following · every ${seconds}s`,
    stop: "ctrl-c stops",
    stopped: (n: number) => (n === 1 ? "stopped · 1 line" : `stopped · ${n} lines`),
    notFollowing: "--follow needs a terminal. Pipe whop apps logs directly.",
  },
  dates: {
    presets: "Presets: --last 7d, --last 30d, --last 90d, --this month, --last month.",
    badPreset: (what: string) => `${what} is not a date preset.`,
    both: (preset: string) => `Give --from and --to, or --${preset}, not both.`,
    rangeHint: (days: number, from: string, to: string) => `${days} days from ${from} to ${to}. Try --last 30d, or move --from and --to closer together.`,
    titles: {
      BAD_PRESET: "Not a date preset",
      EVENTS_RANGE: "Whop would refuse this range",
    } as Record<string, string>,
  },
  home: {
    balance: "Balance",
    revenue: (days: number) => `Net revenue · ${days}d`,
    range: (from: string, to: string) => `${from} to ${to}`,
    notSignedIn: "Not signed in. Run whop login.",
  },
  spinner: {
    running: (argv: string[]) => `Running ${shellJoin(["whop", ...argv])}…`,
    identity: "Checking who you are…",
    money: "Checking who you are, the balance, and the payout method…",
    adplan: "Checking the campaign, the page, the payment method, and estimating reach…",
    home: "Running auth status, ledgers report, stats get…",
    gtm: "Running stats get, people list, audiences list, ad-campaigns list, promo-codes list…",
    doctor: "Checking who you are…",
    current: "Reading the record as it is…",
    launch: "Reading the product, the account, the connected pages, and a reach estimate…",
    winback: "Reading the campaign, the people seen in the window, the connected pages, and a reach estimate…",
    rank: "Reading the campaign and its ad groups…",
    moneyScreen: "Reading balances, payout limits, saved methods, reserves, and recent payouts…",
    close: "Reading the balance, the saved methods, and Whop's payout limits…",
    lookup: "Finding the customer, then their memberships, payments, disputes, and cases…",
    dev: "Reading the app, its builds, domains, webhooks, and the last day of errors…",
    store: "Reading products, plans, active promo codes, and checkout links…",
    report: "Reading two weeks of six metrics, then the doctor, the funnel, the money, the store, the campaigns, and the recommendations…",
    price: "Reading the plan…",
    publish: "Reading the product and its plans…",
    hook: "Reading the credential, its scopes, and the existing webhooks…",
    refund: "Reading the payment…",
    dispute: "Reading the dispute…",
    launchStep: (label: string) => `Creating the ${label}…`,
    allPages: (n: number) => `Fetching page ${n}…`,
    sandbox: "Pinging the sandbox host…",
    doctorReads: "Running auth list, permissions check, verifications list, payouts methods, people list, products list, webhooks list…",
    doctorDeliveries: "Running webhooks deliveries…",
  },
  session: {
    hints: {
      idle: "tab completes · ↑↓ history · ! raw whop · help · esc esc quits",
      completing: "tab cycles · enter picks · esc closes",
    },
    mode: (mode: Mode) => mode,
    tip: "Tip",
    /** [prefix, command, suffix]. One is shown at random under the banner. */
    tips: [
      ["Type ", "1", " after a list to open that row"],
      ["Type ", "!login", " to run raw whop with the terminal"],
      ["Press ", "tab", " after a list to complete the ids on screen"],
      ["Type ", "copy 1", " to put a row's id on the clipboard"],
      ["Type ", "copy json", " to put the agent command under the last view on the clipboard"],
      ["Type ", "next", " after a list to fetch the following page"],
      ["Type ", "help products", " to see one group's commands"],
      ["Type ", "home", " for balance and a 7-day revenue sparkline"],
      ["Type ", "gtm", " for the funnel, audiences, campaigns, offers, and launch gaps"],
      ["Type ", "doctor", " to see whether this business is set up to sell"],
    ] as [string, string, string][],
    copied: (id: string) => `Copied ${id}`,
    noTeach: "Nothing to copy yet. Run a list or a get first.",
    noNext: "No next page. The last list ended, or nothing has been listed yet.",
    more: "next for more",
    rows: (n: number) => (n === 1 ? "1 opens the row" : `1–${n} opens a row`),
    pick: (n: number) => (n === 1 ? "↑↓ or 1 picks the row · ↵ opens" : `↑↓ or 1–${n} picks a row · ↵ opens`),
    picked: (n: number) => `↵ opens row ${n} · esc clears`,
    welcome: (version: string) => `${version} · wv session`,
    bye: "bye",
    noRow: (n: number, max: number) => (max === 0 ? "No list on screen to pick a row from." : `Row ${n} is not on screen. Rows go 1 to ${max}.`),
    noGet: (group: string) => `${group} has no get command.`,
    needsTerminal: (what: string) => `wv ${what} needs a terminal. Pipe whop directly.`,
    running: (cmd: string) => cmd,
  },
  /** A playbook as one plan: the card, the run, the done-when footer. Shared by launch and winback. */
  recipe: {
    blocked: "blocked · nothing runs",
    steps: "Steps",
    runs: "runs",
    skipped: "skipped",
    blockerMark: "✗",
    warnMark: "!",
    warning: (n: number) => `${n} ${n === 1 ? "write runs" : "writes run"} in order against production, each with its own idempotency key. A step that fails stops the rest; what was created stays, and the card names it.`,
    fullArgv: "every argv",
    done: (name: string) => (name === "launch" ? "Launched" : name === "winback" ? "Winback is live" : name === "close" ? "Month closed" : name === "refund" ? "Refunded" : name === "dispute" ? "Evidence submitted" : name === "hook" ? "Webhook is live" : name === "price" ? "Price changed" : name === "publish" ? "Published" : "Done"),
    stopped: "Stopped",
    failed: "failed",
    notRun: "not run",
    resume: "Rerun the same command to resume: every step carries its idempotency key, so the finished ones return what they made.",
    blockedMessage: (name: string) => `The ${name} cannot run as planned. Every blocker is listed in plan.blockers; fix them, then plan again.`,
    typeAmount: (amount: string, name: string) => `Type ${amount} to run the ${name}`,
  },
  /** `wv report`: the Monday brief. */
  report: {
    title: "report",
    mdTitle: (account: string) => `${account} · weekly brief`,
    window: (from: string, to: string, prevFrom: string, prevTo: string) => `${from} to ${to} vs ${prevFrom} to ${prevTo}`,
    generated: (at: string) => `generated ${at}`,
    cols: { metric: "metric", thisWeek: "this week", lastWeek: "last week", change: "change" },
    metrics: { page_visits: "visits", new_users: "new users", gross_revenue: "gross revenue", net_revenue: "net revenue", ad_spend: "ad spend", churn_rate: "churn" } as Record<string, string>,
    status: "Status",
    blockers: "Blockers",
    campaigns: "Campaigns",
    recommendations: "Recommendations",
    next: "Next",
    money: "money",
    store: "store",
    people: "people",
    gap: "gap",
    fix: "fix",
    payoutsBlocked: "payouts blocked (identity)",
    payoutsOk: "payouts allowed",
    storeLine: (sale: number, products: number, codes: number) => `${sale} of ${products} ${products === 1 ? "product" : "products"} for sale · ${codes} active ${codes === 1 ? "code" : "codes"}`,
    noCampaigns: "No live campaigns.",
    noRecommendations: "Nothing ready from Whop's recommender.",
    approve: (title: string) => `approve: ${title}`,
    approveShort: "approve",
    unblockPayouts: "unblock payouts",
    nothingToDo: "Nothing to do this week.",
    md: "markdown",
  },
  /** `wv store`: the catalog on one screen; `wv store price` and `wv store publish`: recipes. */
  store: {
    title: "store",
    products: "Products",
    plans: "plans",
    offers: "Offers",
    checkouts: "Checkout links",
    forSale: "for sale",
    members: (n: number) => `${n} ${n === 1 ? "member" : "members"}`,
    stock: (n: number) => `${n} left`,
    trial: (days: number) => `${days}-day trial`,
    waitlist: "waitlist",
    notVisible: (visibility: string) => `${visibility}: not for sale until published`,
    noPlans: "The product has no plan, so there is nothing to buy. wv plans create --product_id <prod> --help.",
    noPlansShort: "no plans",
    noVisiblePlan: "Every plan is hidden or archived, so the page has nothing to buy. Publish a plan: wv plans update <plan> --visibility visible.",
    noProducts: "No products yet. wv products create --title <name>.",
    noOffers: "No active promo codes.",
    noCheckouts: "No checkout links. wv store publish <prod> mints one for the default plan.",
    moreCheckouts: (n: number) => `+${n} more · whop checkout-configurations list --format json`,
    anyone: "anyone",
    never: "never",
    cols: { code: "code", off: "off", who: "who", uses: "uses", expires: "expires" },
    publish: "publish",
    price: "price",
    price_: {
      title: "Change a price",
      stepLabel: "price",
      planKey: "plan",
      membersKey: "on it now",
      renewal: "renewal",
      priceKey: "price",
      first: "first charge",
      needsPlan: "Which plan? wv store price <plan_id> --to 39 [--initial 0]. wv store lists them.",
      needsAmount: "What to? --to <amount> for the price (the renewal on a subscription), --initial <amount> for a subscription's first charge.",
      unknownFlag: (flag: string) => `${flag} is not a price flag. wv store price takes --to and --initial.`,
      noPlan: (id: string, err: string) => `${id} could not be read${err ? `: ${err}` : ""}.`,
      minimum: (min: string) => `A paid plan charges at least ${min}; 0 makes it free.`,
      samePrice: (price: string) => `The plan is already ${price}.`,
      initialOnOneTime: "--initial is for subscriptions; a one-time plan has one price, --to.",
      archived: "The plan is archived; unarchive it first: wv plans update <plan> --visibility visible.",
      members: (n: number, renewal: boolean) => (renewal ? `${n} ${n === 1 ? "member is" : "members are"} on this plan. The API reference does not say whether a renewal price change applies to them; check the dashboard before assuming it does not.` : `${n} ${n === 1 ? "member has" : "members have"} bought this plan at the old price; that does not change.`),
      check: "plan",
    },
    publish_: {
      title: "Publish a product",
      stepLabels: { publish: "publish", link: "checkout link" } as Record<string, string>,
      publishLine: (title: string) => `${title} goes visible on the store and the marketplace`,
      alreadyVisible: "already visible",
      alreadyVisibleShort: "already visible",
      linkLine: (plan: string, price: string) => `a shareable checkout for ${plan} · ${price}`,
      linkLineNoPlan: "a shareable checkout for the default plan",
      noLink: "--no-link",
      linkKey: "link for",
      pageKey: "page",
      noCopy: "The product has no headline and no description; the page will be bare. wv products update <prod> --headline … --description ….",
      needsProduct: "Which product? wv store publish <prod_id> [--no-link]. wv store lists them.",
      unknownFlag: (flag: string) => `${flag} is not a publish flag. wv store publish takes --no-link.`,
      noProduct: (id: string, err: string) => `${id} could not be read${err ? `: ${err}` : ""}.`,
      check: { product: "product", link: "checkout" },
    },
  },
  /** `wv dev`: the app loop on one screen; `wv dev hook`: a webhook created, tested, proven. */
  dev: {
    title: "dev",
    app: "app",
    type: "type",
    url: "url",
    verified: "verified",
    unverified: "not verified",
    noUrl: "not deployed yet · whop apps deploy",
    noApps: "No apps yet. whop apps init starts one.",
    builds: "Builds",
    domains: "Domains",
    webhooks: "Webhooks",
    noBuilds: "No builds yet. whop apps deploy makes the first.",
    noDomains: "No custom domains. wv domains create --app_id <app> --domain <host>.",
    noWebhooks: "No webhooks. wv dev hook https://<host>/hooks --plan.",
    live: "production",
    enabled: "on",
    disabled: "off",
    healthy: "—",
    failing: (n: number, since?: string) => `${n} failing${since ? ` · since ${since}` : ""}`,
    errors: (n: number) => (n === 0 ? "No error lines in the last 24 hours." : `${n} error ${n === 1 ? "line" : "lines"} in the last 24 hours · wv apps logs <app> --level error`),
    cols: { platform: "platform", status: "status", production: "prod", created: "created", domain: "domain", dns: "dns", cert: "cert", checked: "checked", url: "url", enabled: "enabled", events: "events", failures: "failures" },
    deploy: "deploy",
    follow: "logs",
    hook: "webhook",
    oauth: "This login is an OAuth token, which cannot manage webhooks.",
    keyLacksScope: "The active API key lacks developer:manage_webhook.",
    forbidden: "Whop answered 403 to webhooks list; the key may be scoped to another account.",
    fixIs: (fix: string[]) => (fix.length ? `Fix: ${fix.join(" ")}.` : ""),
    hookTitle: "Add a webhook",
    stepLabels: { hook: "webhook", test: "test event" } as Record<string, string>,
    hookLine: (n: number, host: string, app?: string) => `${n} ${n === 1 ? "event" : "events"} to ${host}${app ? ` · for ${app}` : " · for the account"}`,
    testLine: (event: string) => `send a ${event} test payload and read the response`,
    scope: "scope",
    account: "the account",
    credential: "credential",
    apiKeyOk: "API key with developer:manage_webhook",
    needsUrl: "Which URL? wv dev hook https://<host>/hooks [--events a,b] [--app app_x] [--test event].",
    hookFlags: (flag: string) => `${flag} is not a hook flag. wv dev hook takes --events, --app, --test.`,
    needsHttps: (url: string) => `${JSON.stringify(url)} is not an https URL. Whop signs payloads and sends them over TLS only.`,
    badEvent: (event: string) => `${JSON.stringify(event)} is not an event name. Dot form, like payment.succeeded; wv agent webhooks lists the enum.`,
    exists: (id: string) => `A webhook for this URL already exists: ${id}. Change its events with wv webhooks update ${id} --events …, or delete it first.`,
    testNotSubscribed: (event: string) => `--test ${event} is not among the subscribed events; the test still sends, but real ${event} events will not.`,
    check: { delivery: "delivery", hook: "webhook", screen: "the loop" },
  },
  /** `wv support lookup`: one customer on one screen; `wv support refund` and `wv support dispute`: recipes. */
  support: {
    title: "support",
    who: "who",
    email: "email",
    spent: "spent",
    over: (n: number) => `over ${n} ${n === 1 ? "purchase" : "purchases"}`,
    seen: "seen",
    firstSeen: (when: string) => `first ${when}`,
    lastSeen: (when: string) => `last ${when}`,
    from: (source: string) => `from ${source}`,
    member: "member",
    joined: (date: string) => `joined ${date}`,
    lastAccess: (when: string) => `last access ${when}`,
    kinds: { email: "email", user: "user id", membership: "membership id", payment: "payment id", member: "member id", person: "person id", license: "license key" } as Record<string, string>,
    notFound: (key: string, kind: string) => `Nothing found for ${key} as ${kind}. Try the email, the user id, a membership id, a license key, or a payment id.`,
    memberships: "Memberships",
    payments: "Payments",
    cases: "Disputes and cases",
    noMemberships: "No memberships.",
    noPayments: "No payments.",
    noCases: "No disputes or cases.",
    cancels: "cancels at period end",
    oneTime: "one-time",
    chargeback: "chargeback",
    inquiry: "inquiry",
    case: "case",
    passed: "passed",
    soon: "soon",
    cols: { product: "product", status: "status", until: "until", amount: "amount", refunded: "refunded", reason: "reason", date: "date", kind: "kind", due: "due" },
    actions: { refund: "refund", extend: "extend", cancel: "cancel", dispute: "respond", reply: "reply" },
    needsKey: "Who? wv support lookup <email | user_id | mem_id | license key | pay_id>.",
    refund: {
      title: "Refund a payment",
      stepLabel: "refund",
      payment: "payment",
      refundedSoFar: "refunded so far",
      refundNow: "refund now",
      partial: "partial",
      full: "in full",
      fullLine: (amount: string) => `${amount} back to the buyer's payment method · in full`,
      partialLine: (amount: string, remaining: string) => `${amount} of ${remaining} remaining · partial`,
      needsPayment: "Which payment? wv support refund <pay_id> [--amount N]. wv support lookup <email> lists them.",
      unknownFlag: (flag: string) => `${flag} is not a refund flag. wv support refund takes --amount.`,
      noPayment: (id: string, err: string) => `${id} could not be read${err ? `: ${err}` : ""}.`,
      notPaid: (status: string) => `The payment is ${status}, not paid; there is nothing to refund.`,
      notRefundable: "Whop marks this payment as not refundable (refundable: false). The dashboard says why.",
      nothingLeft: (total: string) => `The ${total} payment is already refunded in full.`,
      overRemaining: (amount: string, remaining: string) => `${amount} is more than the ${remaining} left to refund.`,
      partialBefore: (refunded: string) => `${refunded} was already refunded on this payment; this refund is on top of it.`,
      disputeAlerted: "This payment carries a dispute alert. A refund now may resolve it before it becomes a chargeback; check wv support lookup for the alert.",
      check: { refund: "refund", payment: "payment" },
    },
    dispute: {
      title: "Respond to a dispute",
      stepLabels: { evidence: "evidence", submit: "submit" } as Record<string, string>,
      dispute: "dispute",
      due: "due",
      payment: "payment",
      hoursLeft: (h: number) => `${h} ${h === 1 ? "hour" : "hours"} left`,
      passedShort: "window closed",
      evidenceLine: (n: number, types: string) => `${n} ${n === 1 ? "document" : "documents"} · ${types} · replaces what was uploaded before`,
      submitLine: "send the evidence to the processor · final",
      needsDispute: "Which dispute? wv support dispute <dsp_id> --evidence file_x[:type] …. wv disputes list --status needs_response shows the open ones.",
      unknownFlag: (flag: string) => `${flag} is not a dispute flag. wv support dispute takes --evidence file_id[:document_type], repeatable.`,
      badEvidence: (part: string) => `--evidence wants a file id like file_x or file_x:product_image, not ${JSON.stringify(part)}. Upload with wv files create first.`,
      badType: (type: string, allowed: string) => `${type} is not a document type. One of ${allowed}.`,
      noDispute: (id: string, err: string) => `${id} could not be read${err ? `: ${err}` : ""}.`,
      notOpen: (status: string) => `The dispute is ${status}; only needs_response takes evidence.`,
      locked: (reason: string) => `Evidence is locked${reason ? `: ${reason}` : ""}. Nothing more can be submitted.`,
      passed: (due: string) => `The evidence window closed at ${due}.`,
      soon: (h: number) => `${h} hours left. Whop reserves the last 24 hours before the processor's cutoff, so submit today.`,
      noEvidence: "No evidence named. Submitting without documents loses the dispute; add --evidence file_id[:type] for each document (wv files create uploads one).",
      inquiry: "This is an inquiry, not a chargeback yet: no funds have moved, and a good response here can end it.",
      replaces: (n: number) => `${n} ${n === 1 ? "document is" : "documents are"} already uploaded; upload_evidence replaces the full set, so name them again if they should stay.`,
      check: { status: "status" },
    },
  },
  /** `wv money`: treasury on one screen; `wv money close`: month end as one plan. */
  money: {
    title: "money",
    balances: "Balances",
    limits: "Payout limits",
    methods: "Saved payout methods",
    reserves: "Reserves",
    recent: "Recent payouts",
    available: "available",
    upTo: (max: string) => `up to ${max} per payout`,
    blocked: "blocked",
    noLimits: "Whop did not return limits (the payout:withdrawal:read scope may be missing).",
    noMethods: "No saved payout method. Add one: whop payouts create-method --help, or the dashboard.",
    noMethodsRead: (err: string) => `The saved payout methods could not be read: ${err}`,
    methodMissing: (id: string) => `${id} is not among the saved payout methods. wv payouts methods lists them.`,
    severalMethods: "Several saved payout methods and none is the default. Name one with --method <potk_id>.",
    severalShort: "several · name one with --method",
    isDefault: "default",
    noPayouts: "No payouts yet.",
    cols: { amount: "amount", status: "status", speed: "speed", created: "created" },
    releases: (date: string) => `releases ${date}`,
    blockedNote: "Payouts are blocked until identity verification completes. Everything else on this screen still works; the close plan will refuse until the block lifts.",
    close: "month end",
    closeTitle: "Close the month",
    stepLabels: { export: "ledger export", payout: "payout" } as Record<string, string>,
    exportLine: (period: string, currency: string) => `financial activity for ${period} in ${currency} · CSV, ready in minutes`,
    payoutLine: (amount: string, to: string, speed: string) => `${amount} to ${to} · ${speed}`,
    methodTbd: "a saved method",
    defaultNotes: (period: string) => `Month end ${period}`,
    balance: "balance",
    keep: "keep",
    payout: "payout",
    window: "window",
    noBalance: (currency: string, err: string) => `The ${currency} balance could not be read: ${err}`,
    nothingToPay: (available: string, keep: string) => `Nothing to pay out: ${available} available, ${keep} kept. Lower --keep or wait for settlement.`,
    payoutsBlocked: (reason: string) => `Whop blocks payouts on this account: ${reason}`,
    instantUnknown: "Whop returned no instant limit for this account; the payout may be refused as not eligible for instant. --speed standard is the safe choice.",
    unknownFlag: (flag: string) => `${flag} is not a close flag. wv money close takes --keep, --method, --currency, --speed, --period, --notes.`,
    badSpeed: (speed: string) => `--speed is standard or instant, not ${JSON.stringify(speed)}.`,
    badPeriod: (period: string) => `--period is last or this, not ${JSON.stringify(period)}.`,
    check: { export: "export", payout: "payout", balance: "balance after" },
  },
  /** `wv gtm winback`: the winback playbook as one plan. */
  winback: {
    title: "Win back visitors who did not buy",
    stepLabels: { visitors: "visitors audience", customers: "customers audience", group: "ad group" } as Record<string, string>,
    visitorsName: (days: number) => `visited ${days}d, no purchase`,
    customersName: "customers",
    visitorsLine: (days: number, seen?: string) => `people-filter · seen in ${days} days · never bought · contactable · refreshes${seen ? ` · ~${seen} people now` : ""}`,
    customersLine: "people-filter · has bought · refreshes · excluded from the ad group",
    promoLine: (code: string, amount: string) => `${code} · ${amount} off · churned customers · one per customer`,
    groupLine: (days: number, campaign: string) => `winback ${days}d · in ${campaign || "the campaign"} · includes visitors, excludes customers`,
    campaign: "campaign",
    needsCampaign: "--budget needs --campaign <adcamp_id>: the ad group joins an existing campaign. wv ad-campaigns list shows them; wv gtm launch creates one.",
    noCampaign: (id: string, err: string) => `${id} could not be read: ${err}`,
    noVisitors: (days: number) => `Nobody was seen in the last ${days} days, so the visitors audience will be empty until the pixel attributes traffic. wv doctor names the fix.`,
    noBudget: "no --budget",
    unknownFlag: (flag: string) => `${flag} is not a winback flag. wv gtm winback takes --campaign, --budget, --days, --code, --amount, --product, --countries.`,
    check: { visitors: "visitors ready", customers: "customers ready", group: "group", rank: "in three days" },
  },
  /** `wv gtm rank <campaign>`: the decide rubric as one read. */
  rank: {
    title: "rank",
    noGroups: "No ad groups under this campaign yet.",
    cols: { group: "ad group", delivery: "delivery", age: "age", spend: "spend", results: "results", cpr: "cpr", roas: "roas", verdict: "verdict" },
    verdicts: { scale: "scale", hold: "hold", wait: "wait", pause: "pause", not_delivering: "not delivering", rejected: "rejected" } as Record<string, string>,
    noTarget: "No --target, so no pause or scale verdicts: name the cost per result one sale is worth (price × margin) and rerun. Groups under 3 days or 50 results wait regardless.",
    targetNote: (target: string, days: number, results: number, ratio: number) => `Target ${target} per result. A group waits until ${days} days and ${results} results; over ${ratio}× the target it is a pause, under the target a scale. One change per campaign per day; duplicate a winner instead of editing it.`,
    needsCampaign: "Which campaign? wv gtm rank <adcamp_id> [--target 30]. wv ad-campaigns list shows them.",
  },
  /** `wv gtm launch`: the launch-day playbook as one plan. */
  launch: {
    title: "Launch a product",
    blocked: "blocked · nothing runs",
    steps: "Steps",
    runs: "runs",
    skipped: "skipped",
    product: "product",
    spend: "spend",
    reach: "reach",
    paysFrom: "pays from",
    runsUnder: "runs under",
    noEnd: "no end date",
    campaignTitle: "Launch",
    defaultHeadline: "It is live",
    defaultPrimary: (percent: number, code: string) => `${percent}% off this week with ${code}.`,
    stepLabels: { promo: "promo code", checkout: "checkout link", campaign: "campaign", ad: "ad" } as Record<string, string>,
    promoLine: (code: string, percent: number, days: number, stock?: number) => `${code} · ${percent}% off · new customers · ${days} ${days === 1 ? "day" : "days"}${stock ? ` · ${stock} uses` : ""}`,
    checkoutLine: (plan: string, price?: string) => `${plan}${price ? ` · ${price}` : ""} · tagged with the campaign`,
    campaignLine: "Meta · sales · budget on the ad group",
    adLine: (creatives: number, countries: string, ages: [number, number]) => `${creatives} ${creatives === 1 ? "creative" : "creatives"} · ${countries} · ages ${ages[0]}–${ages[1]} · destination is the checkout link`,
    warning: (n: number) => `${n} ${n === 1 ? "write runs" : "writes run"} in order against production, each with its own idempotency key. A step that fails stops the rest; what was created stays, and the card names it.`,
    blockerMark: "✗",
    warnMark: "!",
    noProduct: (id: string) => `${id} could not be read. Check the id with wv products list.`,
    noPlan: "The product has no default plan, so there is nothing to sell at checkout. Create a plan first: wv plans create --help.",
    notVisible: (visibility: string) => `The product is ${visibility}. Publish it before the ad runs: wv products publish <id>.`,
    noPage: "No Meta page is connected, so the ad write will refuse. wv doctor names the fix.",
    noPayment: "No ads payment method on the account, so the campaign cannot deliver. Add one in the dashboard, or leave --budget off.",
    noBudget: "no --budget",
    noCreative: "no --creative file_id, so the ad is skipped. Generate one with wv media generate, then rerun with --creative.",
    overCap: (total: string, cap: string) => `The daily budget commits ${total} over 30 days, more than the ${cap} cap wv allows per ad write (WV_AD_CAP).`,
    paymentMethods: (n: number) => (n === 1 ? "the account's ads payment method" : `${n} ads payment methods on the account`),
    typeBudget: (amount: string) => `Type ${amount} to launch`,
    done: "Launched",
    stopped: "Stopped",
    failed: "failed",
    notRun: "not run",
    resume: "Rerun the same command to resume: every step carries its idempotency key, so the finished ones return what they made.",
    check: {
      promo: "promo",
      checkout: "checkout",
      campaign: "campaign",
      ad: "ad",
      delivery: "spend tomorrow",
      gtm: "the funnel",
    },
    unknownFlag: (flag: string) => `${flag} is not a launch flag. wv gtm launch takes --product, --budget, --code, --percent, --days, --stock, --creative, --headline, --primary-text, --countries, --ages, --url, --campaign.`,
    extraArg: (arg: string) => `Unexpected argument ${arg}. The product id is the only positional.`,
    needsProduct: "Which product? wv gtm launch <prod_id> --budget 40 --creative file_x.",
    badNumber: (flag: string, value: string) => `${flag} needs a positive number, not ${JSON.stringify(value)}.`,
    badAges: (value: string) => `--ages is two ages like 25-44, not ${JSON.stringify(value)}.`,
    fullArgv: "every argv",
    blockedMessage: "The launch cannot run as planned. Every blocker is listed in plan.blockers; fix them, then plan again.",
  },
  /** `wv agent [group]`: Markdown a program reads. */
  manifest: {
    generated: (version: string, group: string) => `${version ? version + " · " : ""}generated by wv from \`whop ${group} <verb> --schema\`. The schema is the truth; rerun \`wv agent ${group}\` after \`whop upgrade\`.`,
    protocol: (group?: string) => [
      "## Writes go through wv",
      "",
      `Run reads as \`whop ${group ?? "<group>"} <verb> … --format json\`. Run every write as \`wv ${group ?? "<group>"} <verb> …\` instead of \`whop\`. Without \`--yes\` wv does not run it: it exits 2 with a JSON envelope whose \`error.code\` is \`CONFIRMATION_REQUIRED\`, whose \`plan\` is what the write commits (account, flags, amount, balance, caps, and for ads the campaign tree, reach, and committed spend), and whose \`rerun\` is the argv that runs it, carrying an \`--approve\` token bound to that exact command that expires in ten minutes. Show the plan to the person, then run \`rerun\` unchanged. \`--plan\` returns \`{ ok: true, plan }\` and runs nothing. Refusals come back the same way with no \`rerun\`: \`WHOP_LIMIT\` (Whop's own limit, in its words), \`WV_CAP\` (\`WV_PAYOUT_CAP\`), \`INSUFFICIENT_BALANCE\`, \`WV_AD_CAP\` (\`WV_AD_CAP\`). \`--format json\` does not lift the gate. Every write also takes \`--idempotency-key\`; generate it from the plan step, not the call, so a retry never writes twice.`,
    ],
    prereqs: (checks: string) => `Before the first write, run \`wv doctor --format json\` and make sure these checks are \`ok\`: ${checks}. Each failing check carries its \`fix\` command.`,
    jsonSpellings: [
      "## Object and array flags",
      "",
      "`whop` takes objects and arrays as JSON on the command line: `--ad_group '{\"budget_amount\":40}'`, `--headlines '[\"a\",\"b\"]'`. Through `wv` three more spellings assemble to the same JSON: a dotted path (`--ad_group.budget_amount 40`), a repeated flag for an array (`--headlines a --headlines b`), and `@file.json` for a whole value. Plain JSON is never rewritten.",
    ],
    datePresets: "Date flags on `stats get` and `events list` accept presets through `wv`: `--last 7d`, `--last 30d`, `--this month`, `--last month`. They resolve to `--from` and `--to` before `whop` runs; `events list` refuses a range over 30 days in Whop's words.",
    datePresetsShort: "Through wv: `--last 7d`, `--this month`, `--last month` resolve to `--from`/`--to`.",
    jsonShort: "Object and array flags take JSON; through wv, dotted paths, repeated flags, and `@file` also work.",
    gated: (money: boolean) => (money ? "Moves money. Run through `wv`; without `--yes` it returns the plan and exits 2." : "Writes. Run through `wv`; without `--yes` it returns the plan and exits 2."),
    commands: "Commands",
    indexCols: ["command", "kind", "description"],
    cols: ["flag", "type", "required", "description"],
    yes: "yes",
    no: "no",
    noFlags: "No flags.",
    args: (list: string) => `Arguments: ${list}`,
    noSchema: (group: string, verb: string) => `No schema: \`${verb}\` is a command group. Run \`whop ${group} ${verb} --help\`.`,
    oneOf: (values: string) => `One of ${values}.`,
    defaultIs: (value: string) => `Default \`${value}\`.`,
    example: (value: string) => `Example \`${value}\`.`,
    indexIntro: (version: string) => `${version ? version + ". " : ""}One page per command group: \`wv agent <group>\` prints every verb's flags from \`--schema\`, marks the verbs that write, move money, or destroy, and names the setup checks the group depends on. Between \`whop --llms\` (no flags) and \`whop --llms-full\` (338 KB).`,
    unknownGroup: (group: string) => `\`${group}\` is not a whop command group. \`wv agent\` lists them.`,
  },
  /** The gate as an agent reads it: one JSON envelope on stdout, no prompt. */
  agent: {
    confirm: (cmd: string, mode: Mode) => `${cmd} writes to ${mode}. wv did not run it.`,
    confirmHint: (minutes: number) => `Show the plan to the person. Run the command in \`rerun\` to run it; its --approve token matches this exact command and expires in ${minutes} ${minutes === 1 ? "minute" : "minutes"}. Add --plan to see the plan and run nothing.`,
    planHint: (cmd: string) => `Plan only; nothing ran, and --yes beside --plan does nothing. To run it: ${cmd} (without --plan) returns CONFIRMATION_REQUIRED with a rerun; run that rerun exactly as given.`,
    approvalExpired: "The approval expired. Run the command without --approve for a fresh plan and a new rerun.",
    approvalInvalid: "The approval does not match this command. It was minted for a different argv, mode, or machine. Run the command without --approve for a fresh plan.",
    needsTerminal: (what: string) => `wv ${what} draws a screen and needs a terminal. wv doctor and wv gtm answer JSON in a pipe.`,
  },
};

const VERB_TITLES: Record<string, string> = {
  create: "Create",
  update: "Update",
  delete: "Delete",
  cancel: "Cancel",
  pause: "Pause",
  resume: "Resume",
  publish: "Publish",
  unpublish: "Unpublish",
  deploy: "Deploy",
  transfer: "Transfer",
  duplicate: "Duplicate",
  invite: "Invite to",
  extend: "Extend",
  replay: "Replay",
  retry_payment: "Retry payment for",
  transfer_ownership: "Transfer ownership of",
  form_company: "Form company for",
};

const GROUP_NOUNS: Record<string, string> = {
  payouts: "a payout",
  products: "a product",
  plans: "a plan",
  memberships: "a membership",
  "ad-campaigns": "an ad campaign",
  "ad-groups": "an ad group",
  ads: "an ad",
  apps: "an app",
  transfers: "a transfer",
  swaps: "a swap",
  cards: "a card",
  deposits: "a deposit",
  bounties: "a bounty",
  webhooks: "a webhook",
  "promo-codes": "a promo code",
  "api-keys": "an API key",
};

function titleVerb(v: string) {
  return v.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}
