// Every string a person reads.

import { shellJoin } from "./argv.ts";

export type Mode = "production" | "sandbox";

const duration = (seconds: number) => (seconds % 60 === 0 ? `${seconds / 60} minute${seconds === 60 ? "" : "s"}` : `${seconds} seconds`);

export const copy = {
  list: {
    of: (n: number, total: number | null) => (total == null || total === n ? `${n} ${n === 1 ? "row" : "rows"}` : `${n} of ${total}`),
    noMore: "no more pages",
    next: (cursor: string) => `next: --after ${cursor}`,
    /** `noun` is the group, or the verb when it names a sub-resource: `payouts methods` has no methods yet, not no payouts. */
    empty: (noun: string) => `No ${noun.replace(/[-_]/g, " ")} yet.`,
    emptyHint: (group: string) => ["whop", group, "create", "--help"],
    json: "json",
  },
  summary: {
    total: (n: number) => `${n} total`,
    facet: (facet: string) => `By ${facet.replace(/_/g, " ")}`,
    empty: "Nothing to count yet.",
  },
  detail: {
    sections: {
      identity: "Identity",
      status: "Status",
      money: "Money",
      dates: "Dates",
      relations: "Relations",
      other: "Details",
    },
    yes: "yes",
    no: "no",
    empty: "—",
    /** A boolean the hints name as the status: `success` on a webhook delivery. */
    ok: "ok",
    failed: "failed",
  },
  confirm: {
    title: (group: string, verb: string) => `${VERB_TITLES[verb] ?? titleVerb(verb)} ${GROUP_NOUNS[group] ?? group.replace(/-/g, " ")}`,
    badge: (mode: Mode) => (mode === "sandbox" ? "writes to sandbox" : "writes to production"),
    warning: "This runs against production. The Whop CLI has no dry-run.",
    sandboxWarning: "This runs against the sandbox host. No real money moves.",
    money: "This moves real money.",
    expires: (seconds: number) => `The prompt expires in ${duration(seconds)}.`,
    question: "Run it?",
    yesNo: "[y/N]",
    /** Money: the person types the amount back. `y` is not consent for a payout. */
    typeAmount: (amount: string) => `Type ${amount} to send it`,
    amountNo: (amount: string) => `[${amount}/N]`,
    aborted: "Not run.",
    expired: (seconds: number) => `Not run. The prompt sat for ${duration(seconds)}.`,
    /** Row labels the money gate adds on top of the flags. */
    to: "to",
    from: "from",
    balance: "balance",
    cap: "cap",
    available: (available: string, after: string) => `${available} available · ${after} after`,
    perPayout: (cap: string) => `${cap} per payout`,
    /** Whop's live limit for the chosen speed sits next to wv's own cap. */
    whopLimit: (max: string, speed: string) => `${max} ${speed} from Whop`,
    wvCap: (cap: string) => `${cap} from wv`,
    dailyLeft: (left: string) => `${left} left today`,
    noCap: "none",
    unknownMethod: "not among the saved payout methods",
    tryFirst: "try first",
    refused: {
      cap: "Over the payout cap",
      balance: "Over the available balance",
      whop: "Whop would refuse this payout",
      whopBody: (amount: string, max: string, speed: string) => `${amount} is more than the ${max} Whop allows per ${speed} payout right now.`,
      badge: "not run",
      capBody: (amount: string, cap: string) => `${amount} is more than the ${cap} cap wv allows per payout.`,
      balanceBody: (amount: string, available: string) => `${amount} is more than the ${available} available in this currency.`,
      raise: (dollars: number) => `Raise it for one shell with WV_PAYOUT_CAP=${dollars}, or turn it off with WV_PAYOUT_CAP=none.`,
      sandbox: "Try it against the sandbox first:",
    },
  },
  adplan: {
    planBadge: "plan only · nothing runs",
    planNote: "Nothing was written. Run the command without --plan to be asked.",
    thenRun: "then",
    money: "Spend accrues as ads deliver and is charged afterward.",
    reachErrorNote: "Whop could not estimate reach, so the create may fail the same way.",
    /** Row keys. */
    campaign: "campaign",
    group: "group",
    ad: "ad",
    reachKey: "reach",
    spend: "spend",
    paysFrom: "pays from",
    runsUnder: "runs under",
    /** Sub-row keys. */
    objective: "objective",
    platform: "platform",
    budget: "budget",
    status: "status",
    goal: "goal",
    targeting: "targeting",
    runs: "runs",
    creative: "creative",
    url: "url",
    new: "new",
    day: "day",
    lifetime: "lifetime",
    onGroups: "on each ad group",
    on: (event: string) => `on ${event.replace(/_/g, " ")}`,
    window: (from?: string, to?: string) => (from && to ? `${from} to ${to}` : from ? `from ${from}` : `until ${to}`),
    creatives: "creatives",
    headline: "headline",
    headlines: "headlines",
    text: "primary text",
    texts: "primary texts",
    description: "description",
    descriptions: "descriptions",
    boostsPost: "boosts an existing post",
    excluding: (n: number) => `excluding ${n} ${n === 1 ? "place" : "places"}`,
    automaticAudience: "automatic audience",
    automaticPlacements: "automatic placements",
    placements: (platforms: string[]) => `placements on ${platforms.join(", ")}`,
    ages: (lo?: number, hi?: number) => (lo !== undefined && hi !== undefined ? `ages ${lo}–${hi}` : lo !== undefined ? `ages ${lo}+` : `ages up to ${hi}`),
    audiences: (names: string[]) => `audiences: ${names.join(", ")}`,
    excludingAudiences: (names: string[]) => `excluding: ${names.join(", ")}`,
    reach: (range: string, platform: string) => `${range} people on ${platform}`,
    reachNone: (platform: string) => `${platform} returned no estimate for this targeting`,
    reachFailed: (message: string) => `not estimated · ${message}`,
    reachSkipped: "not estimated · no targeting on the command line",
    openEnded: (total: string, days: number) => `${total} over ${days} days · no end date`,
    until: (total: string, days: number) => `${total} over ${days} ${days === 1 ? "day" : "days"}`,
    fromExisting: (owner: string) => `from the existing ${owner} budget`,
    noBudget: "none yet · nothing delivers until a budget exists",
    noPaymentMethod: "no ads payment method on the account",
    available: (amount: string) => `${amount} available`,
    noSocial: "no page connected · whop social-accounts connect --platform meta_business --scopes advertise",
    cap: (cap: string) => `${cap} committed spend per plan from wv`,
    typeBudget: (amount: string) => `Type ${amount} to create it`,
    refused: {
      title: "Over the ad spend cap",
      body: (total: string, cap: string) => `This plan commits ${total}, more than the ${cap} cap wv allows per ad write.`,
      raise: (dollars: number) => `Raise it for one shell with WV_AD_CAP=${dollars}, set an end date so the commitment is real, or turn it off with WV_AD_CAP=none.`,
    },
  },
  error: {
    titles: {
      COMMAND_NOT_FOUND: "Not a command",
      HTTP_400: "Whop refused the request",
      HTTP_404: "Not found",
      HTTP_422: "Whop refused the request",
      UNAVAILABLE: "Not available on this business yet",
      HTTP_401: "Not signed in",
      HTTP_403: "Missing permission",
      HTTP_429: "Rate limited",
      VALIDATION_ERROR: "Missing or invalid flags",
      UNKNOWN: "Whop returned an error",
      NOT_JSON: "Not a JSON response",
      ENOENT: "Whop CLI not found",
      NO_TTY: "Needs a terminal",
      SANDBOX_AUTH: "The sandbox refused this login",
      JSON_FLAGS: "Could not assemble the JSON flag",
    } as Record<string, string>,
    fixes: {
      HTTP_401: "whop login",
      HTTP_403: "whop login --api-key",
      SANDBOX_AUTH: "wv sandbox status",
      ENOENT: "curl -fsSL https://whop.com/install.sh | sh",
    } as Record<string, string>,
    fix: "fix",
    /** What unlocks a feature gate, in one line each. */
    gates: {
      preference: "A preference on the business turns it on; nothing to buy.",
      internal: "Whop-internal only. No plan or preference unlocks it outside Whop.",
      cards: "Card issuing needs a verified identity first; Whop opens the Rain account once verification passes.",
      unknown: "Whop turns this on per business. No CLI preference is known for it; ask Whop, or look in the dashboard.",
    },
    field: (path: string, msg: string) => `--${path}  ${msg}`,
    suggested: "Suggested commands:",
  },
  help: {
    hint: "type wv <group> --help",
    groupHint: (group: string) => `type wv ${group} <command> --help`,
    api: "API",
  },
  gtm: {
    title: "gtm",
    window: (days: number, from: string, to: string) => `last ${days} days · ${from} to ${to}`,
    funnel: "Funnel",
    visits: "store visits",
    newUsersKey: "new users",
    revenue: "gross revenue",
    adSpend: "ad spend",
    peopleTitle: "People",
    seen: (days: number) => `seen · ${days}d`,
    people: (seen: string, customers: number, contactable: number, attributed: number) => `${seen} people · ${customers} customers · ${contactable} contactable · ${attributed} attributed to a source`,
    noPeople: "nobody seen in the window",
    audiences: "Audiences",
    none: "—",
    noAudiences: "none yet · whop audiences create --help",
    lookalike: "lookalike",
    members: (n: number) => `${n} people`,
    campaigns: "Campaigns",
    noCampaigns: "No campaigns yet.",
    try: "try",
    offers: "Offers",
    noOffers: "none yet · whop promo-codes create --help",
    off: "off",
    newUsers: "new buyers only",
    churned: "churned buyers only",
    existing: "existing members only",
    uses: (uses: number, stock?: number) => (stock !== undefined && Number.isFinite(stock) ? `${uses} of ${stock} used` : `${uses} used`),
    expires: (date: string) => `expires ${date}`,
    gapsTitle: "Before a launch",
    fix: "fix",
    gap: {
      pixel: "No visit carries a source: the pixel is not installed on your pages, so nothing is attributed.",
      page: "No Meta page is connected, so every ad command will refuse.",
      payment: "No ads payment method on the account, so ads will not deliver.",
      ei: "Economic Intelligence is off, so `whop economic-intelligence` returns 403.",
    },
  },
  doctor: {
    title: "doctor",
    fix: "fix",
    dashboard: "dashboard only",
    labels: {
      auth: "signed in",
      identity: "identity",
      apiKey: "api key",
      pixel: "pixel",
      page: "meta page",
      payment: "ads payment",
      ei: "intelligence",
      products: "products",
      webhooks: "webhooks",
    },
    notSignedIn: "Not signed in.",
    verification: (status: string) => `verification ${status.replace(/_/g, " ")}`,
    payoutsBlocked: (reason: string) => `Payouts are blocked: ${reason}`,
    payoutsAllowed: (max: string) => `payouts allowed · up to ${max} per standard payout`,
    limitsUnreadable: (err: string) => `Could not read the payout limits · ${err}`,
    limitsMissing: "This login cannot read the payout limits (needs payout:withdrawal:read), so identity is unknown.",
    keyActive: (name: string) => `profile ${name} · api key · every checked scope granted`,
    keyLacks: (name: string, actions: string[]) => `profile ${name} · api key · lacks ${actions.join(", ")} · edit the key in the dashboard`,
    oauthFine: (alt: string) => `oauth · every checked scope granted · api-key profile ${alt} also saved`,
    oauthLacks: (actions: string[], alt: string) => `This oauth login lacks ${actions.join(", ")}. The api-key profile ${alt} is saved; switch to it for those.`,
    noKey: "No api-key profile. Webhooks and the other developer scopes refuse an oauth login.",
    noKeyLacks: (actions: string[]) => `No api-key profile, and this oauth login lacks ${actions.join(", ")}. Mint a key in the dashboard, then save it as a profile.`,
    noPeople: "Nobody has been seen yet, so the pixel is unverified.",
    attributed: (attributed: number, seen: number) => `${attributed} of ${seen} people attributed to a source`,
    paymentOn: (n: number) => (n === 1 ? "1 ads payment method on the account" : `${n} ads payment methods on the account`),
    eiOn: "on",
    noProducts: "No products. Nothing can be bought.",
    noSellable: (n: number) => `${n} ${n === 1 ? "product" : "products"}, none visible with a plan. Nothing can be bought.`,
    forSale: (n: number, title: string, price: string) => (n === 1 ? `1 for sale · ${title} · ${price}` : `${n} for sale · ${title} · ${price} · ${n - 1} more`),
    webhooksScope: "Webhooks refuse an oauth login. Sign in with an API key to list, create, or test them.",
    noWebhooks: "No webhooks. Your server hears nothing when someone pays.",
    delivered: (url: string, when: string) => `${url} · last success ${when}`,
    noDelivery: (url: string, days: number) => `${url} · no successful delivery in ${days} days`,
    more: (n: number) => `${n} more`,
    blocking: (n: number) => `${n} blocking`,
    warnings: (n: number) => `${n} ${n === 1 ? "warning" : "warnings"}`,
    ok: (n: number) => `${n} ok`,
  },
  sandbox: {
    title: "sandbox",
    reachable: "reachable",
    unreachable: "not reachable with this key",
    host: "host",
    key: "key",
    account: "account",
    noKey: "none · every call will answer 401",
    source: (source: "env" | "config" | "default" | "none", configPath: string) => (source === "env" ? "from the shell" : source === "config" ? `from ${configPath}` : source === "default" ? "Whop's published sandbox server" : ""),
    badge: "sandbox · no key",
    missingTitle: "The sandbox needs its own key",
    rejectsOauth: "The sandbox host answers every call with 401 unless it gets a sandbox API key; your production login does not work there.",
    whereFrom: "Whop's API reference lists the host but not where its keys are issued, so get one from Whop.",
    docs: "https://docs.whop.com/developer/api/getting-started",
    saveHint: (configPath: string) => `wv keeps it in ${configPath}, owner-only, so no shell variable is needed. WV_SANDBOX_KEY still wins when set.`,
    askKey: "Paste a sandbox key to save it, or press enter to continue without one",
    askHint: "[whop_…/enter]",
    saved: (configPath: string) => `Saved to ${configPath}. Sandbox commands use it from now on.`,
    skipped: "Continuing without a key. Expect 401 from the sandbox host.",
    notAKey: "That does not look like a Whop key (they start with whop_). Nothing saved.",
    keyRejected: (masked: string) => `The sandbox host answered 401 to the key ${masked}. It is not a sandbox key, or it was revoked.`,
    unknownVerb: (verb: string) => `wv sandbox has no '${verb}'. Try wv sandbox status.`,
  },
  jsonFlags: {
    title: "Could not assemble the JSON flag",
    noFile: (path: string) => `@${path}: no such file. A value that starts with @ and names a path is read as JSON.`,
    badFile: (path: string, why: string) => `@${path} is not JSON: ${why}`,
    mixed: (path: string) => `--${path} mixes an array index with an object key on the same node.`,
  },
  license: {
    title: "license",
    valid: "valid",
    invalid: "invalid",
    unknown: "unknown",
    notFound: "No membership carries this key.",
    status: "status",
    product: "product",
    plan: "plan",
    expires: "expires",
    noExpiry: "never · one-time purchase",
    cancels: "cancels then",
    user: "user",
    membership: "membership",
    needsKey: "wv memberships check needs a license key: wv memberships check <key>",
  },
  webhook: {
    title: "webhook test",
    resultTitle: "Test event",
    newest: "Newest delivery",
    result: "result",
    acknowledged: "acknowledged · the endpoint answered 2xx",
    notAcknowledged: "not acknowledged",
    code: "code",
    body: "body",
    event: "event",
    status: "status",
    ok: "ok",
    failed: "failed",
    time: "time",
    seconds: (s: number) => (s < 1 ? `${Math.round(s * 1000)}ms` : `${s.toFixed(2)}s`),
    sent: "sent",
    replayOf: "replay of",
    id: "id",
    noDeliveries: "no delivery recorded yet",
  },
  logs: {
    title: "logs",
    empty: "No log lines in the window. Whop keeps hosted app logs for 7 days.",
    oldestFirst: "oldest first",
    follow: "follow",
    following: (seconds: number) => `following · every ${seconds}s`,
    stop: "ctrl-c stops",
    stopped: (n: number) => (n === 1 ? "stopped · 1 line" : `stopped · ${n} lines`),
    notFollowing: "--follow needs a terminal. Pipe whop apps logs directly.",
  },
  dates: {
    presets: "Presets: --last 7d, --last 30d, --last 90d, --this month, --last month.",
    badPreset: (what: string) => `${what} is not a date preset.`,
    both: (preset: string) => `Give --from and --to, or --${preset}, not both.`,
    rangeHint: (days: number, from: string, to: string) => `${days} days from ${from} to ${to}. Try --last 30d, or move --from and --to closer together.`,
    titles: {
      BAD_PRESET: "Not a date preset",
      EVENTS_RANGE: "Whop would refuse this range",
    } as Record<string, string>,
  },
  home: {
    balance: "Balance",
    revenue: (days: number) => `Net revenue · ${days}d`,
    range: (from: string, to: string) => `${from} to ${to}`,
    notSignedIn: "Not signed in. Run whop login.",
  },
  spinner: {
    running: (argv: string[]) => `Running ${shellJoin(["whop", ...argv])}…`,
    identity: "Checking who you are…",
    money: "Checking who you are, the balance, and the payout method…",
    adplan: "Checking the campaign, the page, the payment method, and estimating reach…",
    home: "Running auth status, ledgers report, stats get…",
    gtm: "Running stats get, people list, audiences list, ad-campaigns list, promo-codes list…",
    doctor: "Checking who you are…",
    sandbox: "Pinging the sandbox host…",
    doctorReads: "Running auth list, permissions check, verifications list, payouts methods, people list, products list, webhooks list…",
    doctorDeliveries: "Running webhooks deliveries…",
  },
  session: {
    hints: {
      idle: "tab completes · ↑↓ history · ! raw whop · help · esc esc quits",
      completing: "tab cycles · enter picks · esc closes",
    },
    mode: (mode: Mode) => mode,
    tip: "Tip",
    /** [prefix, command, suffix]. One is shown at random under the banner. */
    tips: [
      ["Type ", "1", " after a list to open that row"],
      ["Type ", "!login", " to run raw whop with the terminal"],
      ["Press ", "tab", " after a list to complete the ids on screen"],
      ["Type ", "copy 1", " to put a row's id on the clipboard"],
      ["Type ", "copy json", " to put the agent command under the last view on the clipboard"],
      ["Type ", "next", " after a list to fetch the following page"],
      ["Type ", "help products", " to see one group's commands"],
      ["Type ", "home", " for balance and a 7-day revenue sparkline"],
      ["Type ", "gtm", " for the funnel, audiences, campaigns, offers, and launch gaps"],
      ["Type ", "doctor", " to see whether this business is set up to sell"],
    ] as [string, string, string][],
    copied: (id: string) => `Copied ${id}`,
    noTeach: "Nothing to copy yet. Run a list or a get first.",
    noNext: "No next page. The last list ended, or nothing has been listed yet.",
    more: "next for more",
    rows: (n: number) => (n === 1 ? "1 opens the row" : `1–${n} opens a row`),
    pick: (n: number) => (n === 1 ? "↑↓ or 1 picks the row · ↵ opens" : `↑↓ or 1–${n} picks a row · ↵ opens`),
    picked: (n: number) => `↵ opens row ${n} · esc clears`,
    welcome: (version: string) => `${version} · wv session`,
    bye: "bye",
    noRow: (n: number, max: number) => (max === 0 ? "No list on screen to pick a row from." : `Row ${n} is not on screen. Rows go 1 to ${max}.`),
    noGet: (group: string) => `${group} has no get command.`,
    needsTerminal: (what: string) => `wv ${what} needs a terminal. Pipe whop directly.`,
    running: (cmd: string) => cmd,
  },
};

const VERB_TITLES: Record<string, string> = {
  create: "Create",
  update: "Update",
  delete: "Delete",
  cancel: "Cancel",
  pause: "Pause",
  resume: "Resume",
  publish: "Publish",
  unpublish: "Unpublish",
  deploy: "Deploy",
  transfer: "Transfer",
  duplicate: "Duplicate",
  invite: "Invite to",
  extend: "Extend",
  replay: "Replay",
  retry_payment: "Retry payment for",
  transfer_ownership: "Transfer ownership of",
  form_company: "Form company for",
};

const GROUP_NOUNS: Record<string, string> = {
  payouts: "a payout",
  products: "a product",
  plans: "a plan",
  memberships: "a membership",
  "ad-campaigns": "an ad campaign",
  "ad-groups": "an ad group",
  ads: "an ad",
  apps: "an app",
  transfers: "a transfer",
  swaps: "a swap",
  cards: "a card",
  deposits: "a deposit",
  bounties: "a bounty",
  webhooks: "a webhook",
  "promo-codes": "a promo code",
  "api-keys": "an API key",
};

function titleVerb(v: string) {
  return v.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}
