// Every string a person reads.

export type Mode = "production" | "sandbox";

const duration = (seconds: number) => (seconds % 60 === 0 ? `${seconds / 60} minute${seconds === 60 ? "" : "s"}` : `${seconds} seconds`);

export const copy = {
  list: {
    of: (n: number, total: number | null) => (total == null || total === n ? `${n} ${n === 1 ? "row" : "rows"}` : `${n} of ${total}`),
    noMore: "no more pages",
    next: (cursor: string) => `next: --after ${cursor}`,
    empty: (group: string) => `No ${group.replace(/-/g, " ")} yet.`,
    emptyHint: (group: string) => `whop ${group} create --help`,
    json: "json",
  },
  detail: {
    sections: {
      identity: "Identity",
      status: "Status",
      money: "Money",
      dates: "Dates",
      relations: "Relations",
      other: "Details",
    },
    yes: "yes",
    no: "no",
    empty: "—",
  },
  confirm: {
    title: (group: string, verb: string) => `${VERB_TITLES[verb] ?? titleVerb(verb)} ${GROUP_NOUNS[group] ?? group.replace(/-/g, " ")}`,
    badge: (mode: Mode) => (mode === "sandbox" ? "writes to sandbox" : "writes to production"),
    warning: "This runs against production. The Whop CLI has no dry-run.",
    sandboxWarning: "This runs against the sandbox host. No real money moves.",
    money: "This moves real money.",
    expires: (seconds: number) => `The prompt expires in ${duration(seconds)}.`,
    question: "Run it?",
    yesNo: "[y/N]",
    aborted: "Not run.",
    expired: (seconds: number) => `Not run. The prompt sat for ${duration(seconds)}.`,
    /** Row labels the money gate adds on top of the flags. */
    to: "to",
    from: "from",
    balance: "balance",
    cap: "cap",
    available: (available: string, after: string) => `${available} available · ${after} after`,
    perPayout: (cap: string) => `${cap} per payout`,
    noCap: "none",
    unknownMethod: "not among the saved payout methods",
    tryFirst: "try first",
    refused: {
      cap: "Over the payout cap",
      balance: "Over the available balance",
      badge: "not run",
      capBody: (amount: string, cap: string) => `${amount} is more than the ${cap} cap wv allows per payout.`,
      balanceBody: (amount: string, available: string) => `${amount} is more than the ${available} available in this currency.`,
      raise: (dollars: number) => `Raise it for one shell with WV_PAYOUT_CAP=${dollars}, or turn it off with WV_PAYOUT_CAP=none.`,
      sandbox: "Try it against the sandbox first:",
    },
  },
  error: {
    titles: {
      COMMAND_NOT_FOUND: "Not a command",
      HTTP_400: "Whop refused the request",
      HTTP_404: "Not found",
      HTTP_422: "Whop refused the request",
      UNAVAILABLE: "Not available on this business yet",
      HTTP_401: "Not signed in",
      HTTP_403: "Missing permission",
      HTTP_429: "Rate limited",
      VALIDATION_ERROR: "Missing or invalid flags",
      UNKNOWN: "Whop returned an error",
      NOT_JSON: "Not a JSON response",
      ENOENT: "Whop CLI not found",
      NO_TTY: "Needs a terminal",
    } as Record<string, string>,
    fixes: {
      HTTP_401: "whop login",
      HTTP_403: "whop login --api-key",
      ENOENT: "curl -fsSL https://whop.com/install.sh | sh",
    } as Record<string, string>,
    sandboxKey: "The sandbox host does not accept an OAuth login. Put a sandbox API key in WV_SANDBOX_KEY.",
    fix: "fix",
    field: (path: string, msg: string) => `--${path}  ${msg}`,
    suggested: "Suggested commands:",
  },
  help: {
    hint: "type wv <group> --help",
    groupHint: (group: string) => `type wv ${group} <command> --help`,
    api: "API",
  },
  home: {
    balance: "Balance",
    revenue: (days: number) => `Net revenue · ${days}d`,
    range: (from: string, to: string) => `${from} to ${to}`,
    notSignedIn: "Not signed in. Run whop login.",
  },
  spinner: {
    running: (argv: string[]) => `Running whop ${argv.join(" ")}…`,
    identity: "Checking who you are…",
    money: "Checking who you are, the balance, and the payout method…",
    home: "Running auth status, ledgers report, stats get…",
  },
  session: {
    hints: {
      idle: "tab completes · ↑↓ history · ! raw whop · help · esc esc quits",
      completing: "tab cycles · enter picks · esc closes",
    },
    mode: (mode: Mode) => mode,
    tip: "Tip",
    /** [prefix, command, suffix]. One is shown at random under the banner. */
    tips: [
      ["Type ", "1", " after a list to open that row"],
      ["Type ", "!login", " to run raw whop with the terminal"],
      ["Press ", "tab", " after a list to complete the ids on screen"],
      ["Type ", "copy 1", " to put a row's id on the clipboard"],
      ["Type ", "copy json", " to put the agent command under the last view on the clipboard"],
      ["Type ", "help products", " to see one group's commands"],
      ["Type ", "home", " for balance and a 7-day revenue sparkline"],
    ] as [string, string, string][],
    copied: (id: string) => `Copied ${id}`,
    noTeach: "Nothing to copy yet. Run a list or a get first.",
    rows: (n: number) => (n === 1 ? "1 opens the row" : `1–${n} opens a row`),
    pick: (n: number) => (n === 1 ? "↑↓ or 1 picks the row · ↵ opens" : `↑↓ or 1–${n} picks a row · ↵ opens`),
    picked: (n: number) => `↵ opens row ${n} · esc clears`,
    welcome: (version: string) => `${version} · wv session`,
    bye: "bye",
    noRow: (n: number, max: number) => (max === 0 ? "No list on screen to pick a row from." : `Row ${n} is not on screen. Rows go 1 to ${max}.`),
    noGet: (group: string) => `${group} has no get command.`,
    needsTerminal: "wv session needs a terminal. Pipe whop directly.",
    running: (cmd: string) => cmd,
  },
};

const VERB_TITLES: Record<string, string> = {
  create: "Create",
  update: "Update",
  delete: "Delete",
  cancel: "Cancel",
  pause: "Pause",
  resume: "Resume",
  publish: "Publish",
  unpublish: "Unpublish",
  deploy: "Deploy",
  transfer: "Transfer",
  duplicate: "Duplicate",
  invite: "Invite to",
  extend: "Extend",
  replay: "Replay",
  retry_payment: "Retry payment for",
  transfer_ownership: "Transfer ownership of",
  form_company: "Form company for",
};

const GROUP_NOUNS: Record<string, string> = {
  payouts: "a payout",
  products: "a product",
  plans: "a plan",
  memberships: "a membership",
  "ad-campaigns": "an ad campaign",
  "ad-groups": "an ad group",
  ads: "an ad",
  apps: "an app",
  transfers: "a transfer",
  swaps: "a swap",
  cards: "a card",
  deposits: "a deposit",
  bounties: "a bounty",
  webhooks: "a webhook",
  "promo-codes": "a promo code",
  "api-keys": "an API key",
};

function titleVerb(v: string) {
  return v.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}
